export const Reports = [
    {
      id: "1",
      title: "Malicious",
      securityVendor: "VT",
      status: 0,
      details: "This result is flagged as malicious",
      lastReported: "2024-08-10",
    },
    {
      id: "2",
      title: "Reported as suspicious",
      securityVendor: "VT",
      status: 2,
      details: "This result has been reported as suspicious",
      lastReported: "2024-08-12",
    },
    {
      id: "3",
      title: "Clean",
      securityVendor: "VT",
      status: 3,
      details: "This result is clean and verified",
      lastReported: "2024-08-15",
    },
    {
      id: "4",
      title: "Malicious",
      securityVendor: "VT",
      status: 0,
      details:
        "This result has been identified as malicious based on recent checks",
      lastReported: "2024-08-08",
    },
    {
      id: "5",
      title: "Reported as suspicious",
      securityVendor: "VT",
      status: 2,
      details: "User reports suggest this result might be suspicious",
      lastReported: "2024-08-14",
    },
    {
      id: "6",
      title: "Clean",
      securityVendor: "VT",
      status: 3,
      details: "This result has been reviewed and confirmed clean",
      lastReported: "2024-08-16",
    },
    {
      id: "7",
      title: "Malicious",
      securityVendor: "VT",
      status: 0,
      details: "Flagged as malicious due to multiple reports",
      lastReported: "2024-08-11",
    },
    {
      id: "8",
      title: "Reported as suspicious",
      securityVendor: "VT",
      status: 2,
      details: "Currently under review for potential suspicious activity",
      lastReported: "2024-08-13",
    },
    {
      id: "9",
      title: "Clean",
      securityVendor: "VT",
      status: 3,
      details: "Verified clean through automated and manual checks",
      lastReported: "2024-08-09",
    },
    {
      id: "10",
      title: "Malicious",
      securityVendor: "VT",
      status: 0,
      details: "Determined malicious based on recent scanning results",
      lastReported: "2024-08-07",
    },
  ];